services:
  web:
    build:
      target: dev
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=change-moi
      - DJANGO_SETTINGS_MODULE=app_portal.settings.dev
    volumes:
      - .:/app
      - data:/app/data