services:
  web:
    build:
      context: .
      target: dev
    environment:
      - DJANGO_SECRET_KEY=very-insecure-secure-key
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=change-moi
      - DJANGO_SETTINGS_MODULE=app_portal.settings.dev
    volumes:
      - .:/app
      - data:/app/data
volumes:
  data: